global:
    checkNewVersion: true
    sendAnonymousUsage: false

log:
    level: ERROR

entryPoints:
    web:
        address: ":80"

api:
    insecure: false
    dashboard: true

providers:
    docker:
        network: "traefik-proxy-mmr-local"
        exposedByDefault: false
        constraints: "Label(`traefik.mmr.environment`,`true`)"

experimental:
    http3: true
